name: aml-justus-pfeifer
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
